apiVersion: v1
entries:
  gateway:
  - apiVersion: v2
    appVersion: 1.12.3
    created: "2022-01-20T13:15:29.87696+01:00"
    description: Helm chart for deploying Istio gateways
    digest: 2aa44f23057123eb0b9da1d5ec3d4f0dc73c6f50a44d73795925050fca1ac7d4
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - gateways
    name: gateway
    sources:
    - http://github.com/istio/istio
    type: application
    urls:
    - gateway-1.12.3.tgz
    version: 1.12.3
generated: "2022-01-20T13:15:29.87588+01:00"
